%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\!\battery\battery\code\python\out.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/02/15 19:54:14

%% Initialize variables.
filename = 'C:\!\battery\battery\code\python\out.csv';
delimiter = '\t';

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,4,5,6,9]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,3,4,5,6,9]);
rawCellColumns = raw(:, [1,7,8]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
path = rawCellColumns(:, 1);
porosity = cell2mat(rawNumericColumns(:, 1));
taux = cell2mat(rawNumericColumns(:, 2));
tauy = cell2mat(rawNumericColumns(:, 3));
tauz = cell2mat(rawNumericColumns(:, 4));
solvetime = cell2mat(rawNumericColumns(:, 5));
dimx = rawCellColumns(:, 2);
dimy = rawCellColumns(:, 3);
dimz = cell2mat(rawNumericColumns(:, 6));


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp me rawNumericColumns rawCellColumns R;



figure;
hold on
scatter(porosity, taux,'b')
scatter(porosity, tauy,'r')
scatter(porosity, tauz,'g')

fx=fit(porosity,taux,'poly2','Exclude', find(tauy == 0))
fy=fit(porosity,tauy,'poly2', 'Exclude',find(tauy == 0))
fz=fit(porosity,tauz,'poly2','Exclude', find(tauz == 0))
plot(fx, 'b')
plot(fy,'r')
plot(fz,'g')

hLeg = legend('example')
set(hLeg,'visible','off')

%plot(fz,porosity,tauz,'g')

xlabel('Porosity | (blue=x, red=y, green=z)') % x-axis label
ylabel('Tortuosity') % y-axis label


